# Generated by Powerlevel10k configuration wizard
# Type `p10k configure` to generate another config.

# Temporarily change options.
'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
  emulate -L zsh -o extended_glob

  # Unset all configuration options.
  unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'

  # Zsh >= 5.1 is required.
  [[ $ZSH_VERSION == (5.<1->*|<6->.*) ]] || return

  # The list of segments shown on the left.
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    dir                     # current directory
    vcs                     # git status
    context                 # user@hostname
    newline                 # \n
    prompt_char             # prompt symbol
  )

  # The list of segments shown on the right.
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    status                  # exit code of the last command
    command_execution_time  # duration of the last command
    background_jobs         # background jobs
    virtualenv              # python virtual environment
    time                    # current time
  )

  # Defines character set used by powerlevel10k.
  typeset -g POWERLEVEL9K_MODE=powerline

  # When set to true, icons appear before content on both sides of the prompt.
  typeset -g POWERLEVEL9K_ICON_BEFORE_CONTENT=

  # Add an empty line before each prompt.
  typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=false

  # Connect left prompt lines with these symbols.
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX='%240F╭─'
  typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX='%240F├─'
  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX='%240F╰─'
  # Connect right prompt lines with these symbols.
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_SUFFIX='%240F─╮'
  typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_SUFFIX='%240F─┤'
  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_SUFFIX='%240F─╯'

  # Filler between left and right prompt on the first prompt line.
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR='─'
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_BACKGROUND=
  typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_GAP_BACKGROUND=
  if [[ $POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR != ' ' ]]; then
    typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_FOREGROUND=240
    typeset -g POWERLEVEL9K_EMPTY_LINE_LEFT_PROMPT_FIRST_SEGMENT_END_SYMBOL='%{%}'
    typeset -g POWERLEVEL9K_EMPTY_LINE_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='%{%}'
  fi

  # Default background color - using a richer dark blue-gray
  typeset -g POWERLEVEL9K_BACKGROUND=235

  # Separator between same-color segments on the left.
  typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='%244F\uE0B1'
  # Separator between same-color segments on the right.
  typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='%244F\uE0B3'
  # Separator between different-color segments on the left.
  typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\uE0B0'
  # Separator between different-color segments on the right.
  typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\uE0B2'

  # Suppress Powerlevel10k instant prompt warning
  typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

  # ============================================================================
  # COLOR CUSTOMIZATIONS
  # ============================================================================
  
  # Directory segment colors - vibrant blue gradient
  typeset -g POWERLEVEL9K_DIR_FOREGROUND=39
  typeset -g POWERLEVEL9K_DIR_BACKGROUND=237
  typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=39
  typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=39
  typeset -g POWERLEVEL9K_DIR_ANCHOR_BOLD=true
  
  # VCS (Git) segment colors - green theme
  typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=76
  typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND=237
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=214
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=237
  typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=220
  typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=237
  
  # Context segment colors - subtle gray
  typeset -g POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND=244
  typeset -g POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND=237
  typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND=196
  typeset -g POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND=237
  
  # Status segment colors - red for errors
  typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=196
  typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND=237
  typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=76
  typeset -g POWERLEVEL9K_STATUS_OK_BACKGROUND=237
  
  # Command execution time colors - yellow for slow commands
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=220
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=237
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3
  
  # Background jobs colors - orange
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=214
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND=237
  
  # Virtual environment colors - purple
  typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND=141
  typeset -g POWERLEVEL9K_VIRTUALENV_BACKGROUND=237
  
  # Time segment colors - cyan
  typeset -g POWERLEVEL9K_TIME_FOREGROUND=117
  typeset -g POWERLEVEL9K_TIME_BACKGROUND=237
  
  # Prompt character colors - bright white with green for success
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_FOREGROUND=76
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_BACKGROUND=237
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_FOREGROUND=196
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_BACKGROUND=237
  
  # Multiline prompt colors - subtle gray
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX='%244F╭─'
  typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX='%244F├─'
  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX='%244F╰─'
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_SUFFIX='%244F─╮'
  typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_SUFFIX='%244F─┤'
  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_SUFFIX='%244F─╯'
  
  # ============================================================================
  # ADDITIONAL ENHANCEMENTS
  # ============================================================================
  
  # Enable icons for better visual appeal
  typeset -g POWERLEVEL9K_ICON_BEFORE_CONTENT=true
  
  # Show directory path with better formatting
  typeset -g POWERLEVEL9K_DIR_TRUNCATE_BEFORE_MARKER=false
  typeset -g POWERLEVEL9K_DIR_TRUNCATE_AFTER_MARKER=true
  typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=80
  typeset -g POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS=40
  typeset -g POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS_PCT=50
  
  # Git status formatting
  typeset -g POWERLEVEL9K_VCS_BRANCH_ICON='\uF126 '
  typeset -g POWERLEVEL9K_VCS_COMMIT_ICON='\uF73C '
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON='\uF059 '
  typeset -g POWERLEVEL9K_VCS_UNSTAGED_ICON='\uF071 '
  typeset -g POWERLEVEL9K_VCS_STAGED_ICON='\uF055 '
  
  # Time format
  typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%H:%M:%S}'
  
  # Command execution time format
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT='%d s'
  
  # Background jobs format
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=true

  # If p10k is already loaded, reload configuration.
  (( ! $+functions[p10k] )) || p10k reload
}

# Tell `p10k configure` which file it should overwrite.
typeset -g POWERLEVEL9K_CONFIG_FILE=${${(%):-%x}:a}

(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'